### ISSUE TITLE
博客【樱花庄的白猫】临时留言板

### ISSUE THREAD

**Issue by mashirozx** [mashirozx/Comments#13]
> ![image](https://user-images.githubusercontent.com/16148054/58555775-f15c6380-824c-11e9-880c-f866f8faa757.png)

在此之前留言请发在这里（**可以为自己的留言开新 issue，不要求一定在此贴下评论**😃），留言时请把需要留言的页面地址粘贴过来，之后我会搬到博客上的。如果不想一直收到某条评论下的回复提醒邮件可以点右侧的 Unsubscribe 按钮。

![image](https://user-images.githubusercontent.com/16148054/58555874-37192c00-824d-11e9-832c-245e687d15b7.png)

**Comment by yqchilde** [comment]
emmm 博主您好，请问我更换了主题之后这样子是哪里问题啊
![image](https://user-images.githubusercontent.com/36953759/58611000-2665c600-82e0-11e9-9fd0-5a82579088b6.png)

**Comment by yqchilde** [comment]
就是其他内容全是空白，数据库里是有文章的

**Comment by yqchilde** [comment]
哈哈  是我眼拙，知道了，看到说明了

**Comment by cnguu** [comment]
![image](https://user-images.githubusercontent.com/10758182/58621278-959ce380-82fb-11e9-8f95-d997c62134d8.png)

想给你留言来着，发现评论关闭了，哈哈

**Comment by momo296859251** [comment]
大佬，https://2heng.xin/music/   歌单页面播放器加载你是如何做到加载很快的，我用你的主题，加了音乐播放器，老是加载不出来，要刷新两三遍才会出来

**Comment by yqchilde** [comment]
为什么楼上两位的评论在我邮箱收到了，emmm
![image](https://user-images.githubusercontent.com/36953759/58621681-88342900-82fc-11e9-8629-e9d05ff29546.png)
同时我想请教一个问题，就是相册功能怎么开启

**Comment by cnguu** [comment]
> 为什么楼上两位的评论在我邮箱收到了，emmm
> ![image](https://user-images.githubusercontent.com/36953759/58621681-88342900-82fc-11e9-8629-e9d05ff29546.png)
> 同时我想请教一个问题，就是相册功能怎么开启

因为这是同一个issue

**Comment by yqchilde** [comment]
emmm 好吧，请问楼上大佬，你知道相册功能怎么开启吗？

**Comment by momo296859251** [comment]
相册的话，直接在编辑器里添加图片，同一篇文章内的所有图片会自动形成一个相册
![QQ截图20190530171257](https://user-images.githubusercontent.com/25020323/58622488-4f954f00-82fe-11e9-8867-38e2f0508a59.png)

**Comment by yqchilde** [comment]
好的，成功了，谢谢你

**Comment by mashirozx** [comment]
@yqchilde @momo296859251 插入相册可以用主题里的短代码<https://github.com/mashirozx/Sakura/wiki/Fancybox>

**Comment by mashirozx** [comment]
> 大佬，https://2heng.xin/music/ 歌单页面播放器加载你是如何做到加载很快的，我用你的主题，加了音乐播放器，老是加载不出来，要刷新两三遍才会出来

插入歌单可以用 Herimt-X 插件

**Comment by momo296859251** [comment]
> > 大佬，[https：](https://2heng.xin/music/) //2heng.xin/music/歌单页面播放器加载你是如何做到加载很快的，我用你的主题，加了音乐播放器，老是加载不出来，要刷新两三遍才会出来
> 
> 插入歌单可以用Herimt-X插件

我用的就是Herimt-X这个插件，但是页面加载歌单很慢，我看过控制台加载情况，加载歌单3.1M大小，有时候打开加载不出来，要刷新一遍才出来，但是打开你的页面就不用刷新，很快就加载出来了。是我服务器带宽太低吗？还是大佬有特殊的姿势_(:з」∠)_

**Comment by mashirozx** [comment]
> > > 大佬，[https：](https://2heng.xin/music/) //2heng.xin/music/歌单页面播放器加载你是如何做到加载很快的，我用你的主题，加了音乐播放器，老是加载不出来，要刷新两三遍才会出来
> > 
> > 
> > 插入歌单可以用Herimt-X插件
> 
> 我用的就是Herimt-X这个插件，但是页面加载歌单很慢，我看过控制台加载情况，加载歌单3.1M大小，有时候打开加载不出来，要刷新一遍才出来，但是打开你的页面就不用刷新，很快就加载出来了。是我服务器带宽太低吗？还是大佬有特殊的姿势_(:з」∠)_

不知道诶，试试我的歌单吧
```
[hermit autoplay="false" mode="circulation" preload="none"]netease_playlist#:3319320[/hermit]
```

**Comment by yqchilde** [comment]
@mashirozx 大佬，请问鼠标样式的js你放在了哪个里面，我想修改为没有特效的

**Comment by mashirozx** [comment]
> @mashirozx 大佬，请问鼠标样式的js你放在了哪个里面，我想修改为没有特效的

那是css样式，比如<https://github.com/mashirozx/Sakura/blob/master/style.css#L149>

参考<https://developer.mozilla.org/zh-CN/docs/Web/CSS/cursor>

**Comment by Xinak** [comment]
@mashirozx 大佬你好，我根据SS/SSR 拯救之道去设置了，结果提示Unable to resolve host"www.google.com":No address associated with hostname，然后测试网络的时候也是无互联网连接，请问是我的方法不对吗？
![TIM图片20190530175429](https://user-images.githubusercontent.com/51194889/58625008-1d86eb80-8304-11e9-9878-1ff1441ba60d.jpg)

**Comment by yqchilde** [comment]
@mashirozx 我将style.css 里面的所有 cursor都换成了default，但是网站上鼠标还是有特效

**Comment by mashirozx** [comment]
> @mashirozx 大佬你好，我根据SS/SSR 拯救之道去设置了，结果提示Unable to resolve host"www.google.com":No address associated with hostname，然后测试网络的时候也是无互联网连接，请问是我的方法不对吗？
> ![TIM图片20190530175429](https://user-images.githubusercontent.com/51194889/58625008-1d86eb80-8304-11e9-9878-1ff1441ba60d.jpg)

应该是无法连接到你的代理服务器吧，检查一下ssr配置是否正确（话说现在用UDP转发也上不了p站的

**Comment by mashirozx** [comment]
> @mashirozx 我将style.css 里面的所有 cursor都换成了default，但是网站上鼠标还是有特效

刷新缓存、CDN切换为本地调用

**Comment by yqchilde** [comment]
@mashirozx 大佬，可能是我没理解相册短链接，我复制了https://github.com/mashirozx/Sakura/wiki/Fancybox
然后是这样子的
![image](https://user-images.githubusercontent.com/36953759/58633765-11a72380-831c-11e9-9743-9e59942ba632.png)

**Comment by yqchilde** [comment]
还有最后一个问题，这个位置点击没反应吗
![image](https://user-images.githubusercontent.com/36953759/58633815-3bf8e100-831c-11e9-9a98-a4dac3e0e249.png)

**Comment by spirit1431007** [comment]
> 还有最后一个问题，这个位置点击没反应吗
> ![image](https://user-images.githubusercontent.com/36953759/58633815-3bf8e100-831c-11e9-9a98-a4dac3e0e249.png)

和设备屏幕或者浏览器缩放有关，尝试调整缩放比，如果不想调的话，偏左一点或者偏右一点的地方可以点击

**Comment by yqchilde** [comment]
@spirit1431007  谢谢大佬，确实是点左边一点就可以了，你知道相册那个短连接怎么用吗？

**Comment by spirit1431007** [comment]
> @spirit1431007 谢谢大佬，确实是点左边一点就可以了，你知道相册那个短连接怎么用吗？

我这边是正常使用的，检查 [这段代码](https://github.com/mashirozx/Sakura/blob/master/functions.php#L1492) 有没有被屏蔽

**Comment by teaper** [comment]
大佬互加友链！
名字：TEAPER
头像：https://avatars2.githubusercontent.com/u/37693348?s=460&v=4
博客：https://www.teaper.dev
说明：博客写的像日志

**Comment by Sora98** [comment]
成功使用了pixiv的本地反代的方法，但是打开P站页面的速度很慢，大概20秒，还有概率无法加载图片，请问一下是什么原因，要怎么解决

**Comment by lm1997** [comment]
大佬您好 virtual hosts闪退怎么办 点进去瞬间就会关闭

**Comment by mashirozx** [comment]
> 大佬互加友链！
> 名字：TEAPER
> 头像：https://avatars2.githubusercontent.com/u/37693348?s=460&v=4
> 博客：https://www.teaper.dev
> 说明：博客写的像日志

已添加，.dev域名多少钱一年呢？

**Comment by mashirozx** [comment]
> 成功使用了pixiv的本地反代的方法，但是打开P站页面的速度很慢，大概20秒，还有概率无法加载图片，请问一下是什么原因，要怎么解决

那改用代理服务器试试吧

**Comment by mashirozx** [comment]
> 大佬您好 virtual hosts闪退怎么办 点进去瞬间就会关闭

试试下载最新版apk：<https://github.com/x-falcon/Virtual-Hosts/releases>

**Comment by lm1997** [comment]
> > 大佬您好虚拟主机闪退怎么办点进去瞬间就会关闭
> 
> 试试下载最新版apk：[https：/github.com/x-Falcon/虚拟主机/发行版](https://github.com/x-falcon/Virtual-Hosts/releases)

成了大佬 多谢

**Comment by teaper** [comment]
GoDaddy购买的dev域名，现在有折扣，只要60一年，我之前买好像98还是89来着

**Comment by lm1997** [comment]
> > 大佬您好 virtual hosts闪退怎么办 点进去瞬间就会关闭
> 
> 试试下载最新版apk：https://github.com/x-falcon/Virtual-Hosts/releases

新的问题来临了大佬 新版的virtual hosts能进去了 证书安装了 hosts也选了 但是还是进不去p站啊 以前的旧手机试了一下是没问题的

**Comment by mashirozx** [comment]
> GoDaddy购买的dev域名，现在有折扣，只要60一年，我之前买好像98还是89来着

好叭，想要的已经被抢注了 😥

**Comment by mashirozx** [comment]
> > > 大佬您好 virtual hosts闪退怎么办 点进去瞬间就会关闭
> > 
> > 
> > 试试下载最新版apk：https://github.com/x-falcon/Virtual-Hosts/releases
> 
> 新的问题来临了大佬 新版的virtual hosts能进去了 证书安装了 hosts也选了 但是还是进不去p站啊 以前的旧手机试了一下是没问题的

可能是virtual hosts不兼容新手机？你去app那边反馈一下吧<https://github.com/x-falcon/Virtual-Hosts/issues>，告诉他你的机型、系统、cpu

**Comment by asgh215** [comment]
![image](https://user-images.githubusercontent.com/49670081/58765204-e124eb00-85a2-11e9-9d0c-91b46ce84b64.png) 在关闭nginx时，进google时自动跳转了这个页面，请问怎么解决

**Comment by momo296859251** [comment]
大佬，你的《PIL 合并 RGB 通道图与 Alpha 通道图》这篇文章发出来的立绘素材图我都已经给你合并了，800多张图，每两张对应合并到一个文件夹，共400多个文件，合并后的素材在[这里](链接：https://pan.baidu.com/s/1Rp1diRIpuo_1GWOCRzVdzw)提取码：3ff8

**Comment by momo296859251** [comment]
额，链接怎么没了，再发一次 链接：https://pan.baidu.com/s/1Rp1diRIpuo_1GWOCRzVdzw 
提取码：3ff8

**Comment by huozk0804** [comment]
大佬，请问你用的哪家的VPS

**Comment by mashirozx** [comment]
> 大佬，你的《PIL 合并 RGB 通道图与 Alpha 通道图》这篇文章发出来的立绘素材图我都已经给你合并了，800多张图，每两张对应合并到一个文件夹，共400多个文件，合并后的素材在这里提取码：3ff8

感谢，处理好了，共享地址: <https://io.shino.cc/index.php?share/folder&user=1&sid=vRtSdN3p>  提取密码: U9HIc
下面是代码

```python
import os
from PIL import Image

def single_image_merge(image_path, mask_path, merged_path):
    img = Image.open(image_path)
    mas = Image.open(mask_path)

    pixdata_img = img.load()
    pixdata_mas = mas.load()

    for y in range(mas.size[1]):
        for x in range(mas.size[0]):
            pixdata_img[x, y] = (pixdata_img[x, y][0], pixdata_img[x, y][1], pixdata_img[x, y][2], pixdata_mas[x, y][2])

    img.save(merged_path)

# Traversal dir
root_path = 'C:/Users/Mashiro/Downloads/Texture2D/'
save_path = 'C:/Users/Mashiro/Desktop/results/'

id = 1
print('Start.')

for dir in os.listdir(root_path):
    print('Working on... ' + str(id) + '/' + str(len(os.listdir(root_path))))
    id += 1
    for file in os.listdir(root_path + dir):
        if '[alpha]' in file:
            name = file[0: file.find('[alpha]')] + '_merged_' + dir
            mask = file
        else:
            image = file

    image_path = root_path + dir + '/' + image
    mask_path = root_path + dir + '/' + mask
    merged_path = save_path + name + '.png'
    single_image_merge(image_path, mask_path, merged_path)

print('Done.')
```

**Comment by mashirozx** [comment]
> 大佬，请问你用的哪家的VPS

Vultr，下面是邀请链接

<a href="https://www.vultr.com/?ref=7196564"><img src="https://www.vultr.com/media/banner_1.png" width="728" height="90"></a>

**Comment by huozk0804** [comment]
> > 大佬，请问你用的哪家的VPS
> 
> Vultr，下面是邀请链接
> 
> [<img alt="" width="728" height="90" src="https://camo.githubusercontent.com/a0fd21ec6c09e2b1ab4a4b942e8b4d9f04b2a48e/68747470733a2f2f7777772e76756c74722e636f6d2f6d656469612f62616e6e65725f312e706e67">](https://www.vultr.com/?ref=7196564)

你套用了国内的哪个CDN 是又拍云吗，设置的是源站吗

**Comment by huozk0804** [comment]
> > 大佬，请问你用的哪家的VPS
> 
> Vultr，下面是邀请链接
> 
> [<img alt="" width="728" height="90" src="https://camo.githubusercontent.com/a0fd21ec6c09e2b1ab4a4b942e8b4d9f04b2a48e/68747470733a2f2f7777772e76756c74722e636f6d2f6d656469612f62616e6e65725f312e706e67">](https://www.vultr.com/?ref=7196564)
这两天不太平啊 vultr开始十几个实例都是不能用的

**Comment by mashirozx** [comment]
> > > 大佬，请问你用的哪家的VPS
> > 
> > 
> > Vultr，下面是邀请链接
> > [<img alt="" width="728" height="90" src="https://camo.githubusercontent.com/a0fd21ec6c09e2b1ab4a4b942e8b4d9f04b2a48e/68747470733a2f2f7777772e76756c74722e636f6d2f6d656469612f62616e6e65725f312e706e67">](https://www.vultr.com/?ref=7196564)
> 
> 你套用了国内的哪个CDN 是又拍云吗，设置的是源站吗

网页用的又拍云，图片用的七牛云，又拍云那边是IP回源

**Comment by cometwhisk** [comment]
vultr90%都ping不通了吧

**Comment by mashirozx** [comment]
@2845395980 我的还OK，202的ip段

**Comment by cometwhisk** [comment]
真是倒霉

**Comment by cometwhisk** [comment]
搞了好几个也没通

**Comment by Tsukyomy** [comment]
https://i.loli.net/2019/05/07/5cd1a94ce53fc.jpg @mashirozx 大佬这该怎么办啊

**Comment by mashirozx** [comment]
> https://i.loli.net/2019/05/07/5cd1a94ce53fc.jpg @mashirozx 大佬这该怎么办啊

试试直接启动nginx.exe吧

**Comment by kitmanten** [comment]
希望发一个给网站加live2d的详细教程越详细越好

**Comment by tdqf** [comment]
我前段时间弄这个评论  被git给封号了

**Comment by mashirozx** [comment]
@tdqf 还有这种操作？:sweat:

**Comment by zrwkkd** [comment]
mashirozx大佬，我想知道搭建了自己的个人blog后，部署ss用什么协议和混淆好，可以说说你的协议和混淆吗

**Comment by xptk9074** [comment]
文章特色图不显示，单独设置了，文章页面没有特色图，文章列表里可以显示 
www.zbwsh.cn 大神指导一下

**Comment by mashirozx** [comment]
> 文章特色图不显示，单独设置了，文章页面没有特色图，文章列表里可以显示
> [www.zbwsh.cn](http://www.zbwsh.cn) 大神指导一下

![image](https://user-images.githubusercontent.com/16148054/59142095-070b1f00-89eb-11e9-96c4-57001305a904.png)
勿勾选

**Comment by xptk9074** [comment]
![微信截图_20190609160901](https://user-images.githubusercontent.com/18753918/59156657-94c13a00-8ad1-11e9-883a-f6405e9f39dc.png)

音乐播放器这有个小白边，审查元素看了下 在webpack://[name]/./src/css/index.scss  有个position: fixed; 去掉勾选就没有了，问题是在本地找不到 webpack://[name]/./src/css/index.scss 这个文件，大神指导下怎么去除这小白边

**Comment by Tsukyomy** [comment]
> > https://i.loli.net/2019/05/07/5cd1a94ce53fc.jpg @mashirozx 大佬这该怎么办啊
> 
> 试试直接启动nginx.exe吧

没有用啊大佬 打不开

**Comment by mashirozx** [comment]
> ![微信截图_20190609160901](https://user-images.githubusercontent.com/18753918/59156657-94c13a00-8ad1-11e9-883a-f6405e9f39dc.png)
> 
> 音乐播放器这有个小白边，审查元素看了下 在webpack://[name]/./src/css/index.scss 有个position: fixed; 去掉勾选就没有了，问题是在本地找不到 webpack://[name]/./src/css/index.scss 这个文件，大神指导下怎么去除这小白边

这个看起来好像是某个浏览器插件本地调用的吧

**Comment by Tsukyomy** [comment]
> > https://i.loli.net/2019/05/07/5cd1a94ce53fc.jpg @mashirozx 大佬这该怎么办啊
> 
> 试试直接启动nginx.exe吧

是host忘换了 现在行了 多谢！

**Comment by xptk9074** [comment]
现在很流行文章底部 一键升生成海报，希望大佬能够更新一下 能够一键生成海报 

#
![2019060621120280](https://user-images.githubusercontent.com/18753918/60397170-a0f26180-9b7c-11e9-989b-f88d4f25b9e5.png)
