### ISSUE TITLE
谢谢提供的“PIXIV网页版及客户端访问恢复指南”方法

### ISSUE THREAD

**Issue by carlwangcan** [mashirozx/Comments#19]
你好，我是一个不懂得编程的新手插画师，因为最近SSR、hosts之类的封锁，让我上个设计网站都是头疼得要命，无意中发现你的的这个pixiv的反代证书hosts修改方式，真的能上P站，让我觉得真的很神奇。我看了你的hosts代码，大部分指向都是本地的127.0.0.1，而维基百科同样如此，因为不懂编程，于是我照葫芦画瓢把我常上的pinterest网站的那长长的一串host前面的IP也改成了这个，嗯，不出所料果然没成功。哈哈，能方便地讲一下这是什么意思吗，不用专业的说明，就一句话就行，比如说，我没成功的原因是因为其实关键是你的证书里面包含了P站和维基百科的证书吗？

**Comment by mashirozx** [comment]
反代理的原理就叫domain front吧，文章开头给那个链接里有介绍，证书是一方面，不过自己想签哪个网站的证书也都可以的，签证书的方法文章里也有链接。不过最关键的是不是每个网站都能这样访问，比如wiki和p站可以，但Google就不可以。

**Comment by mashirozx** [comment]
你可以在[这里](http://ping.chinaz.com/)找到某个域名**海外的IP**，可能有多个，在自己电脑上ping其中任意一个，如果能ping通，那么应该可以用同样的方法访问，相应地在`/Pixiv-Nginx/conf/nginx.conf`中添加反代规则，类似：
![image](https://user-images.githubusercontent.com/16148054/58890464-3dac1580-871d-11e9-8468-38b0e90cc955.png)

**Comment by carlwangcan** [comment]
好，谢谢解答
