### ISSUE TITLE
mashiro

### ISSUE THREAD

**Issue by zrwkkd** [mashirozx/Comments#20]
我想知道，vps搭建了像是个人博客的网站之后，ss用什么协议和混淆好

**Comment by mashirozx** [comment]
![image](https://user-images.githubusercontent.com/16148054/59096953-e1c8d300-894e-11e9-8d51-7abbef90e1b1.png)

**Comment by zrwkkd** [comment]
tls不用使用参数吗

**Comment by zrwkkd** [comment]
谢谢，再问一下，为什么要使用ctr加密

**Comment by mashirozx** [comment]
我也不知道，别人推荐的
