### ISSUE TITLE
大佬，统计有错误

### ISSUE THREAD

**Issue by huozk0804** [mashirozx/Comments#21]
Warning: Use of undefined constant wp_statistics_pages - assumed 'wp_statistics_pages' (this will throw an Error in a future version of PHP) in /www/wwwroot/huozk.com/wp-content/themes/Sakura/functions.php on line 484。
我是昨天从仓库新下载的，上面是在每篇文章标题下方报的错误，大佬该怎么解决

**Comment by mashirozx** [comment]
fixed in commit [5679530](https://github.com/mashirozx/Sakura/commit/56795304532b0c4c29181e5992083197f6194be9)
