### ISSUE TITLE
求友链~>v<

### ISSUE THREAD

**Issue by idealclover** [mashirozx/Comments#23]
可以来 PY 个友链嘛~//捂脸~
站名：idealclover 
网址：https://idealclover.top 
简介：翠翠酱的个人网站 
头像：https://idealclover.top/icon.jpg 
联系邮箱：idealclover@163.com
可以来逛逛！

**Comment by mashirozx** [comment]
好的！已添加~

**Comment by idealclover** [comment]
PY成功！开心~
（顺便明日方舟也加了好友~ 2333~

**Comment by mashirozx** [comment]
嗯呢～
