### ISSUE TITLE
亲爱的博主，我想请教一下页头的视频该怎么添加 B站的视频连接格式该怎么填写（wp主题的）

### ISSUE THREAD

**Issue by BeiMingXie-K** [mashirozx/Comments#25]
亲爱的博主，我想请教一下页头的视频该怎么添加 B站的视频连接格式该怎么填写（wp主题的）

**Comment by mashirozx** [comment]
不支持b站视频，仅支持直接的视频链接，比如 <https://cloud.moezx.cc/Video/Live%20from%20the%20Flight%20Deck.mp4>
